#pragma once

#include "libavz.h"

#define CHERRY CHERRY_BOMB
#define POTATO POTATO_MINE
#define PUFF PUFF_SHROOM
#define SUN SUN_SHROOM
#define SCAREDY SCAREDY_SHROOM
#define DOOM DOOM_SHROOM
#define LILY LILY_PAD
#define JALA JALAPENO
#define SPIKE SPIKEWEED
#define POT FLOWER_POT
#define KERNEL KERNEL_PULT
#define COFFEE COFFEE_BEAN
#define COB COB_CANNON
